CrmApplication.UI/Controllers/BlogController.cs
using CrmApplication.BLL;
using CrmApplication.DAL.EntitiyFramework;
using CrmApplication.Entites;
using CrmApplication.UI.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CrmApplication.UI.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        PostManager postManager = new PostManager(new EfPostRepository());
        CategoryManager categoryManager = new CategoryManager(new EfCategoryRepository());

        private readonly INotificationService _notificationService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BlogController(INotificationService notificationService, IWebHostEnvironment webHostEnvironment)
        {
            _notificationService = notificationService;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Blog post, IFormFile file)
        {
            post.PostImage = "";
            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        // resim upload işlemi
                        string wwwrootPath = _webHostEnvironment.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(file.FileName);
                        string extension = Path.GetExtension(file.FileName);

                        string newFileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        string path = Path.Combine(wwwrootPath + "/images/post/", newFileName);

                        using (var fileStram = new FileStream(path, FileMode.Create))
                        {
                            file.CopyTo(fileStram);
                        }

                        post.PostImage = newFileName;

                    }
                    postManager.Create(post);
                    _notificationService.Notification(NotifyType.Success, $" {post.PostTitle} isimli ürünü başarılı bir şekilde kayıt edildi.");
                }
                catch (Exception ex)
                {

                    _notificationService.Notification(NotifyType.Error, ex.Message);
                }
            }
            else

                ModelStateController.CheckIt(_notificationService, ModelState);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult CreateBlogPartial()
        {
            List<SelectListItem> categoryvalues = (from x in
                  categoryManager.ListAll()
                                                   select new SelectListItem
                                                   {
                                                       Text = x.CategoryName,
                                                       Value = x.Id.ToString()
                                                   }).ToList();
            ViewBag.CategoryValues = categoryvalues;

            return PartialView("_BlogCreatePartialView", new Blog());
        }
    }
}

CrmApplication.UI/Views/ViewComponents/ModalViewComponent.cs
using CrmApplication.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace CrmApplication.UI.Views.ViewComponents
{
    public class ModalViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string modalId, string headerText, string formId, string buttonText, string buttonClass, string detailDivId)
        {
            ModalViewComponentModel model = new ModalViewComponentModel();
            model.ModalId = modalId;
            model.HeaderText = headerText;
            model.FormId = formId;
            model.ButtonText = buttonText;
            model.ButtonClass = buttonClass;
            model.DetailDivId = detailDivId;

            return View(model);
        }
    }
}

CrmApplication.UI/Views/Blog/Index.cshtml
@model Blog
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="continer">
    <div class="row">
        <div class="col-xl-4 col-md-6" style="position:relative; left:274px; top:10px;">
            <a class="btn btn-success" onclick="openCreateModal('Blog')">Post Oluştur</a>
        </div>
    </div>
</div>

<div>
    @await Component.InvokeAsync("PostList")
</div>



@*POST CREAT İŞLEMİ İÇİN MODAL*@
<vc:modal modal-id="modalBlogCreate" header-text="Post Oluştur" form-id="formBlogCreate" button-class="primary" button-text="Kaydet" detail-div-id="divCreateModalDetail"></vc:modal>

CrmApplication.UI/Views/Blog/_BlogCreatePartialView.cshtml
@model Blog
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" id="formBlogCreate" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PostTitle" class="control-label"></label>
                <input asp-for="PostTitle" class="form-control" />
                <span asp-validation-for="PostTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostContent" class="control-label"></label>
                <input asp-for="PostContent" class="form-control" />
                <span asp-validation-for="PostContent" class="text-danger"></span>
            </div>
            <div class="mb-4">
                <label class="form-label">Kategori Seçiniz</label>
                @Html.DropDownListFor(x=>x.CategoryId,(List<SelectListItem>)ViewBag.CategoryValues,new{@class="form-control"})
            </div>
            <div class="form-group">
                <label asp-for="PostImage" class="control-label"></label>
                <input class="form-control" type="file" name="file" multiple="false" />
            </div>
        </form>
    </div>
</div>