CrmApplication.UI/Controllers/BlogController.cs
using CrmApplication.BLL;
using CrmApplication.DAL.EntitiyFramework;
using CrmApplication.Entites;
using CrmApplication.UI.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CrmApplication.UI.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        PostManager postManager = new PostManager(new EfPostRepository());
        CategoryManager categoryManager = new CategoryManager(new EfCategoryRepository());

        private readonly INotificationService _notificationService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BlogController(INotificationService notificationService, IWebHostEnvironment webHostEnvironment)
        {
            _notificationService = notificationService;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Blog post, IFormFile file)
        {
            post.PostImage = "";
            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        // resim upload işlemi
                        string wwwrootPath = _webHostEnvironment.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(file.FileName);
                        string extension = Path.GetExtension(file.FileName);

                        string newFileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        string path = Path.Combine(wwwrootPath + "/images/post/", newFileName);

                        using (var fileStram = new FileStream(path, FileMode.Create))
                        {
                            file.CopyTo(fileStram);
                        }

                        post.PostImage = newFileName;

                    }
                    postManager.Create(post);
                    _notificationService.Notification(NotifyType.Success, $" {post.PostTitle} isimli ürünü başarılı bir şekilde kayıt edildi.");
                }
                catch (Exception ex)
                {

                    _notificationService.Notification(NotifyType.Error, ex.Message);
                }
            }
            else

                ModelStateController.CheckIt(_notificationService, ModelState);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult CreateBlogPartial()
        {
            List<SelectListItem> categoryvalues = (from x in
                  categoryManager.ListAll()
                                                   select new SelectListItem
                                                   {
                                                       Text = x.CategoryName,
                                                       Value = x.Id.ToString()
                                                   }).ToList();
            ViewBag.CategoryValues = categoryvalues;

            return PartialView("_BlogCreatePartialView", new Blog());
        }
    }
}

CrmApplication.UI/Controllers/CustomerController.cs
using CrmApplication.BLL;
using CrmApplication.DAL.EntitiyFramework;
using CrmApplication.Entites;
using CrmApplication.UI.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CrmApplication.UI.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {

        // toplu şekilde metotları kapatmak için CTRL+M,O
        CustomerManager customerManager = new CustomerManager(new EfCustomerRepository());
        private readonly INotificationService _notificationService;

        public CustomerController(INotificationService notificationService)
        {
            _notificationService = notificationService;
        }

        public IActionResult Index()
        {
            List<Customer> list = customerManager.ListAll();
            return View(list);
        }

        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    customerManager.Create(customer);
                    _notificationService.Notification(NotifyType.Success, $" {customer.CompanyName} isimli müşteriyi başarılı bir şekilde kayıt edildi.");
                }
                catch (Exception ex)
                {

                    _notificationService.Notification(NotifyType.Error, ex.Message);
                }
            }
            else

                ModelStateController.CheckIt(_notificationService, ModelState);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult CreateCustomerPartial()
        {
            return PartialView("_CustomerCreatePartialView",new Customer());
        }

        public IActionResult EditCustomerPartial(int id)
        {
            Customer customer = customerManager.Get(id);
            return PartialView("_CustomerEditPartialView", customer);
        }
        
        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    customerManager.Update(customer);
                    _notificationService.Notification(NotifyType.Success, $" {customer.CompanyName} isimli müşteri başarılı bir şekilde güncellendi.");
                }
                catch (Exception ex)
                {

                    _notificationService.Notification(NotifyType.Error, ex.Message);
                }
            }
            else
                ModelStateController.CheckIt(_notificationService, ModelState);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteCustomerPartial(int id)
        {
            Customer customer = customerManager.Get(id);
            return PartialView("_CustomerDeletePartialView", customer);
        }

        [HttpPost]
        public IActionResult Delete(Customer customer)
        {
            try
            {
                customerManager.Delete(customer);
                _notificationService.Notification(NotifyType.Success, $" {customer.CompanyName} isimli müşteri başarılı bir şekilde silindi.");
            }
            catch (Exception ex)
            {
                _notificationService.Notification(NotifyType.Error, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

CrmApplication.UI/Controllers/EmployeeController.cs
using CrmApplication.BLL;
using CrmApplication.DAL.EntitiyFramework;
using CrmApplication.Entites;
using CrmApplication.UI.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CrmApplication.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EmployeeController : Controller
    {
        // toplu şekilde metotları kapatmak için CTRL+M,O
        EmployeeManager EmployeeManager = new EmployeeManager(new EfEmployeeEepository());
        private readonly INotificationService _notificationService;

        public EmployeeController(INotificationService notificationService)
        {
            _notificationService = notificationService;
        }

        public IActionResult Index()
        {
            List<Employee> list = EmployeeManager.ListAll();
            return View(list);
        }

        [HttpPost]
        public IActionResult Create(Employee Employee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    EmployeeManager.Create(Employee);
                    _notificationService.Notification(NotifyType.Success, $" {Employee.NameSurname} isimli müşteriyi başarılı bir şekilde kayıt edildi.");
                }
                catch (Exception ex)
                {

                    _notificationService.Notification(NotifyType.Error, ex.Message);
                }
            }
            else

                ModelStateController.CheckIt(_notificationService, ModelState);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult CreateEmployeePartial()
        {
            return PartialView("_EmployeeCreatePartialView", new Employee());
        }

        public IActionResult EditEmployeePartial(int id)
        {
            Employee Employee = EmployeeManager.Get(id);
            return PartialView("_EmployeeEditPartialView", Employee);
        }

        [HttpPost]
        public IActionResult Edit(Employee Employee)    
        {
            if (ModelState.IsValid)
            {
                try
                {
                    EmployeeManager.Update(Employee);
                    _notificationService.Notification(NotifyType.Success, $" {Employee.NameSurname} isimli müşteri başarılı bir şekilde güncellendi.");
                }
                catch (Exception ex)
                {

                    _notificationService.Notification(NotifyType.Error, ex.Message);
                }
            }
            else
                ModelStateController.CheckIt(_notificationService, ModelState);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteEmployeePartial(int id)
        {
            Employee Employee = EmployeeManager.Get(id);
            return PartialView("_EmployeeDeletePartialView", Employee);
        }

        [HttpPost]
        public IActionResult Delete(Employee Employee)
        {
            try
            {
                EmployeeManager.Delete(Employee);
                _notificationService.Notification(NotifyType.Success, $" {Employee.NameSurname} isimli müşteri başarılı bir şekilde silindi.");
            }
            catch (Exception ex)
            {
                _notificationService.Notification(NotifyType.Error, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult UpdateEmployeeState(int id)
        {
            var employee = EmployeeManager.Get(id);
            employee.Status = !employee.Status; // true ise false yap tam terse çevir
            EmployeeManager.Update(employee);
            _notificationService.Notification(NotifyType.Success, $" {employee.NameSurname} isimli müşterinin durumu başarılı bir şekilde güncellendi.");

            return Ok();
        }
    }
}

CrmApplication.UI/Controllers/ProductController.cs
using CrmApplication.BLL;
using CrmApplication.DAL.EntitiyFramework;
using CrmApplication.Entites;
using CrmApplication.UI.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CrmApplication.UI.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        // toplu şekilde metotları kapatmak için CTRL+M,O
        ProductManager productManager = new ProductManager(new EfProductRepository());
        private readonly INotificationService _notificationService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(INotificationService notificationService, IWebHostEnvironment webHostEnvironment)
        {
            _notificationService = notificationService;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Product> list = productManager.ListAll();
            return View(list);
        }

        [HttpPost]
        public IActionResult Create(Product product, IFormFile file)
        {
            product.ImageUrl = "";
            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        // resim upload işlemi
                        string wwwrootPath = _webHostEnvironment.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(file.FileName);
                        string extension = Path.GetExtension(file.FileName);

                        string newFileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        string path = Path.Combine(wwwrootPath + "/images/product/", newFileName);

                        using (var fileStram = new FileStream(path, FileMode.Create))
                        {
                            file.CopyTo(fileStram);
                        }

                        product.ImageUrl = newFileName;

                    }
                    productManager.Create(product);
                    _notificationService.Notification(NotifyType.Success, $" {product.Name} isimli ürünü başarılı bir şekilde kayıt edildi.");
                }
                catch (Exception ex)
                {

                    _notificationService.Notification(NotifyType.Error, ex.Message);
                }
            }
            else

                ModelStateController.CheckIt(_notificationService, ModelState);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult CreateProductPartial()
        {
            return PartialView("_ProductCreatePartialView", new Product());
        }

        public IActionResult EditProductPartial(int id)
        {
            Product product = productManager.Get(id);
            return PartialView("_ProductEditParitalView", product);
        }

        [HttpPost]
        public IActionResult Edit(Product product, IFormFile? file)
        {
         
            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        // resim upload işlemi
                        string wwwrootPath = _webHostEnvironment.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(file.FileName);
                        string extension = Path.GetExtension(file.FileName);

                        string newFileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        string path = Path.Combine(wwwrootPath + "/images/product/", newFileName);

                        using (var fileStram = new FileStream(path, FileMode.Create))
                        {
                            file.CopyTo(fileStram);
                        }

                        product.ImageUrl = newFileName;

                    }
                    productManager.Update(product);
                    _notificationService.Notification(NotifyType.Success, $" {product.Name} isimli ürünü başarılı bir şekilde güncellendi.");
                }
                catch (Exception ex)
                {

                    _notificationService.Notification(NotifyType.Error, ex.Message);
                }
            }
            else
                ModelStateController.CheckIt(_notificationService, ModelState);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteProductPartial(int id)
        {
            Product product = productManager.Get(id);
            return PartialView("_ProductDeletePartialView", product);
        }

        [HttpPost]
        public IActionResult Delete(Product product)
        {
            // model dolu gelecek
            try
            {
                productManager.Delete(product);
                _notificationService.Notification(NotifyType.Success, $" {product.Name} isimli ürünü başarılı bir şekilde silindi.");
            }
            catch (Exception ex)
            {
                _notificationService.Notification(NotifyType.Error, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

CrmApplication.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrmApplication.UI</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrmApplication.UI.styles.css" asp-append-version="true" />*@

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">


    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">

    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">

    <!-- Select2 -->
    <link rel="stylesheet" href="~/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">

    <link rel="stylesheet" href="~/plugins/toastr/toastr.min.css">
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">


</head>
<body class="hold-transition sidebar-mini">

    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="~/index3.html" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                        <i class="fas fa-search"></i>
                    </a>
                    <div class="navbar-search-block">
                        <form class="form-inline">
                            <div class="input-group input-group-sm">
                                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-navbar" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-comments"></i>
                        <span class="badge badge-danger navbar-badge">3</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <div class="media">
                                <img src="~/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Brad Diesel
                                        <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">Call me whenever you can...</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <div class="media">
                                <img src="~/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        John Pierce
                                        <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">I got your message bro</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <div class="media">
                                <img src="~/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Nora Silvester
                                        <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">The subject goes here</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                        <i class="fas fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="~/index3.html" class="brand-link">
                <img src="~/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>
            <div class="sidebar">
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a asp-action="Logout" asp-controller="Auth" class="d-block">@User.Identity.Name</a>
                    </div>
                </div>
                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </div>

                @Html.Partial("_MenuPartialView")

            </div>
        </aside>

        @RenderBody();

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.2.0
            </div>
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
        </footer>
        <aside class="control-sidebar control-sidebar-dark">
        </aside>
    </div>

    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Select2 -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <script src="~/dist/js/adminlte.min.js"></script>
    <script src="~/dist/js/demo.js"></script>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>



    <partial name="_Notifications"></partial>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CrmApplication.UI/Views/Shared/_MenuPartialView.cshtml
@using System.Security.Claims

<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-users"></i>

                <p>
                    Cari Hesaplar
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a asp-controller="Customer" asp-action="Index" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Müşteriler</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Supplier" asp-action="Index" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Tedarikçiler</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Blog" asp-action="Index" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Postlar</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a asp-controller="Product" asp-action="Index" class="nav-link">
                <i class="nav-icon far fa-image"></i>
                <p>Ürünler</p>
            </a>
        </li>
        @if (User.FindFirst(ClaimTypes.Role).Value == "Admin")
        {
            <li class="nav-item">
                <a asp-controller="Employee" asp-action="Index" class="nav-link">
                    <i class="nav-icon far fa-user"></i>
                    <p>Personeller</p>
                </a>
            </li>
        }
        <li class="nav-item">
            <a asp-controller="Auth" asp-action="Logout" class="nav-link">
                <i class="nav-icon far fa-lock"></i>
                <p>Güvenli Çıkış</p>
            </a>
        </li>
    </ul>
</nav>

CrmApplication.UI/Views/Shared/_Notifications.cshtml
@using CrmApplication.UI.Services
@inject INotificationService NotificationService
@{
    var notifies = NotificationService.GetNotifications();
    if (notifies != null && notifies.Any())
    {
        foreach (var item in notifies)
        {
            switch (item.Type)
            {
                case NotifyType.Success:
                <script>
                toastr.success('@item.Message')
                </script>
                break;
                case NotifyType.Error:
                <script>
                toastr.error('@item.Message')
                </script>
                break;
                case NotifyType.Warning:
                <script>
                toastr.warning('@item.Message')
                </script>
                break;
            }
        }
    }
}